local text = {}

text.title = {
	"███████╗███████╗███╗   ██╗███████╗ █████╗ ██╗",
	"██╔════╝██╔════╝████╗  ██║██╔════╝██╔══██╗██║",
	"███████╗█████╗  ██╔██╗ ██║███████╗███████║██║",
	"╚════██║██╔══╝  ██║╚██╗██║╚════██║██╔══██║██║",
	"███████║███████╗██║ ╚████║███████║██║  ██║██║",
	"╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝",
}

text.tree = {
	"                                                                    ...                             ",
	"                                               .          ..........,,'''..                         ",
	"                                      ..  ..,,,,..       .,;;;,,,,;,,;,'''.                         ",
	"                                   ..,;,,,',,;;;;,''.. ..,,,,'.'.';,,,.                             ",
	"                                   ....'''';;;;;;,',;,,,,,,,'',',,'',.                              ",
	"                                    ...   ..,;;,,'',;;;:;;;;,;:,,,,;;'',,.........                  ",
	"                             ..'..',,;,...',;;,,,;;;::::;;;,;::;;:::::;:;;:;;cc:;;'.                ",
	"                           .',;,,;,;;,;;,,;;;;;;;;;;,,,,,;,::,;::::;;:c::::cc:c:;;'.                ",
	"                           ..,,''';:::;:::::;;;::cc:;:ccc;:o:';cc:::;;:;;:;'..;c::;..               ",
	"                          ..',,'...,,,,'';,;;,'..,;,.;cc:;,;cc::;::cc:;,;;,. .';::;;:;,,'.          ",
	"                          .'',,,.....   .''''..     .;::::;..:l;,:ccc:::::,,'','..';cc:::,....      ",
	"                                ..'.   .'......  ';:::cc::c:,:lc,',,;,;cll::c:cc:::cc;;;;;;::'.     ",
	"                                  .... ..       .;cccccc::c;,;:l,..',;ldxxocl::c::c::c::;;ccc;.     ",
	"                          .....      .';.   .''..;::::ll;,:;'';llcloolllcc:,:;;clll::col:;;;,'.     ",
	"                  ..   .':c:::;'.      .'..';:::::::::cl;';cccloollllc:::ccclollccc:;,'...          ",
	"          .....'',::'..':cc::::;'.        .';;;::;,;::ll:::c::cddc:,.''..''...';ccll:;,..',,'.      ",
	"         ..',,;::;::,..,:::,...            .,....,;:ccc:;;.. .cxo'       ..   .;ccccllccccccc;.     ",
	"        .....';:;'',;,.''.     ...''',;;;'.',.':ccc:,.  .    .:dl.       .,',;:,....:l;,,'.....     ",
	"              .,;..''.        .;cllllllcc;..,c:,...  ....'',,'cd:.       'ldoc:c:;;:lodl;..,,;:;.   ",
	"            ..,::;;:.          .:lclol:;;,';ll,...',;::;:cc;,:oo;'..''.. .:llllol::lcccllc;,;::,.   ",
	"       ..''',:cc:;:;.   ........;:;:c:::,.'cllolcccc:;;:::;;;ldl::llllc:'..;lllllll:,..,::,,,'..    ",
	"     .,;;;;;;;;'.,;:;,,:ccc:;,;;:::::;:llccoololllllllodddddoodoloddollllcldlccoxxddl::ccc:::;'..   ",
	"    ..','.',;;,'..,::::cc:::;,;;;:::ccloolcclooloxkxl:;,;;:c::loddkxo:,':loooooddoooc;;;:ccc:;,;,.  ",
	"   .''';,..';:;,,;;,;:;:llcccccc;;:lloc,...,lxxxk0K0d,.    .,::ccccll;,,'.':odollllc,,:loolllc:;,.. ",
	"  .,;,',;;,,,.....',;:::cc:cc:loccoookd:;,':xkkOkO0Okl;,'..'clcccllloollolccloooolddclooolccooc:,.  ",
	"  ...   ..','     ..',,;;;;;:ldl:;:cloddxOO0Oxxxxk0xllllol'...'',''';;;coc;;,,:cl:;'...';;;;cc;''.  ",
	"           ',.....   ..;:::cl:,.   .....,cooc,,:ldxxdxxxxkd,.          ..     ..',,'... .';;;c:,.   ",
	"      .',,,;;;::;'....,::;:o:. ...:::cc:,...    .,;codkxdxOxo:,'.              .'colllc;colllllc,.  ",
	"    .;:;:ccc::;'.     .:::odc;:llcloooooooc,        .,loodkkxxddo:;;,..         .,,,;;,.,c:;:clc;'. ",
	"    .''..'...         .'.'co::odc:cooooooc;'.         .:odxxxdoodxxkkl;,.           ......  ......  ",
	"                  ....'.   ':llc::looolll:.            .;ldO0xccloxkxddol;.                         ",
	"                ,::llclc,. .;ollolooc,'...                .'cl:cdxkOkxxdoo,                         ",
	"               .''''''',;;,,;,'......                          'lkKOxdodllc'                        ",
	"                                                                .,lxkdollloo,                       ",
	"                                                                   ,dxdoxxdo;                       ",
	"                                                                    ;dxkkdol;.                      ",
	"                                                                    'oxdoooc'                       ",
	"                                                                   .;ldxxkd,                        ",
	"                                                                 'ldxkkOOOc                         ",
	"                                                               .ckkkO00OOl.                         ",
	"                                                      ..'..  .;okkkO00Okl.                          ",
	"                                                .....'lkkdo;,;cdxkO000Od:,'''........               ",
	"                                          ..';;;lxkdoc:;;;cloxkOKKKXKxodxkxdodxxxo:;;;;;;,...       ",
	"                                    ...':dkOKKxxXKOxc::loxk0KKXXXXKKOlo0K0OO0OkkOOkkkxddollc;,'.... ",
	"                                ..',codlodxOKK0KXkdlloxk0KXXNNNNXOdxkkddxk0XNKOKKOO00kkkxkkkddxdlcoo",
	"                            ..:ccoxk00OOkkO0KXNWXOdxOKXNNNWWWNXK00KXWWXOxdx0K00XXXXXX0000KKxdk00Oxk0",
	"                         .;lxOXXkkOXNK0KXKOxO00KXOxkOO0KXXNNNXXKNWWWWNNNNKO0KXNWWXK0OOKWX0kookOO0XXX",
	"                       .;kXXNWNOo:lOOookkolx0KXNWNN0xO0KXNNWWNNWWWNNNWWWWNNXK0KK0kkO00KKOxdxxkkxxk0X",
	"                     .':kNNXXX0xdddOOOO00000KKXNWWWNK0KKXXNWWWWWNNXXXNNWWNXKOxddddxxkO0Odlcc:;cox0KK",
	"                    .':xKNXOkkkk0KXNWWNNNNNWWNNNWWWN00NNNNNWNNNK00KKKKK00OO000OOkkxxdod0Kko:':kKKNWW",
}

return text
